services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - DATABASE_URL=${DATABASE_URL}
    image: ${PROJECT}/api:${VERSION}
    container_name: ${PROJECT}-api
    ports:
      - 3000:3000
      - 5000:51212
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - ACCESS_TOKEN_EXPIRED_TIME=${ACCESS_TOKEN_EXPIRED_TIME}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - REFRESH_TOKEN_EXPIRED_TIME=${REFRESH_TOKEN_EXPIRED_TIME}
      - FRONTEND_URL=${FRONTEND_URL}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/generated
      - ./uploads:/app/uploads
    depends_on:
      - db

  db:
    image: postgres:16.1
    container_name: ${PROJECT}-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
    volumes:
      - data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: ${PROJECT}-monitor
    ports:
      - 8080:8080
    depends_on:
      - db

  # redis:
  #   image: redis:8.4
  #   ports:
  #     - '6379:6379'

volumes:
  data:
    name: ${PROJECT}-data
