services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - DATABASE_URL=${DATABASE_URL}
    image: ${PROJECT_NAME}/api:${TAG}
    container_name: ${PROJECT_NAME}-api
    restart: on-failure
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - ACCESS_TOKEN_EXPIRED_TIME=${ACCESS_TOKEN_EXPIRED_TIME}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - REFRESH_TOKEN_EXPIRED_TIME=${REFRESH_TOKEN_EXPIRED_TIME}
      - FRONTEND_URL=${FRONTEND_URL}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/generated
      - ./uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16.1
    container_name: ${PROJECT_NAME}-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  adminer:
    image: adminer:5
    container_name: ${PROJECT_NAME}-monitor
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  # redis:
  #   image: redis:8.4
  #   ports:
  #     - '6379:6379'

volumes:
  data:
    name: ${PROJECT_NAME}-data
