services:
  db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: assetdb
      POSTGRES_USER: asset
      POSTGRES_PASSWORD: assetpass
    ports:
      - '5432:5432'
  redis:
    image: redis:8.4
    ports:
      - '6379:6379'
