services:
  db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: assetdb
      POSTGRES_USER: asset
      POSTGRES_PASSWORD: assetpass
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  # redis:
  #   image: redis:8.4
  #   ports:
  #     - '6379:6379'

  api:
    build:
      context: .
      args:
        - DATABASE_URL=${DATABASE_URL}
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://asset:assetpass@db:5432/assetdb
      - ACCESS_TOKEN_SECRET=djaskdlajdakl
      - ACCESS_TOKEN_EXPIRED_TIME=20s
      - REFRESH_TOKEN_SECRET=djsadakldj
      - REFRESH_TOKEN_EXPIRED_TIME=20s
    volumes:
      - ./uploads:/app/uploads
